### ISSUE TITLE
Xcode Version 12.5 give error message for libExponeaSDK.a

### ISSUE THREAD

**Issue by adeem** [exponea/exponea-react-native-sdk#19]
I upgrade to latest Xcode 12.5 and since then I am not able to compile the project. Here is the error message

```
Undefined symbols for architecture x86_64:
  "Swift._ArrayBuffer._copyContents(initializing: Swift.UnsafeMutableBufferPointer<A>) -> (Swift.IndexingIterator<Swift._ArrayBuffer<A>>, Swift.Int)", referenced from:
      generic specialization <serialized, Swift._ArrayBuffer<Swift.Int8>> of Swift._copyCollectionToContiguousArray<A where A: Swift.Collection>(A) -> Swift.ContiguousArray<A.Element> in libExponeaSDK.a(Reachability.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I am not able to submit the app, any solution?

**Comment by paulpop21** [comment]
I have the same issue after upgrading to the latest Xcode. But the error only appears when the app it's using the debug schema. Works for the release schema.

**Comment by Thomas0c** [comment]
I was able to alleviate this issue by following step 3 in this comment here: https://github.com/facebook/react-native/issues/31179#issuecomment-829536845.

**Comment by michaela-dev** [comment]
@adeem When trying on our side, we were able to fix this error by removing both references to "$(TOOLCHAIN_DIR)/usr/lib/swift-5.0/$(PLATFORM_NAME)" from project.pbxproj file. You also need to have a Swift bridging header and an empty swift file in your target. XCode should create bridging header file for you, when you create empty swift file, but if you declined this option once, you will have to create bridging file manually:
https://mycodetips.com/ios/manually-adding-swift-bridging-header-1290.html 
It's basically the same solution as in link from @Thomas0c  and should do the trick.

**Comment by michaela-dev** [comment]
Hi @adeem, the new 0.5.1 release contains a few fixes for the problems faced when working on XCode 12.5. Please let us know if you are still facing this issue, or I can close it. Thanks!

**Comment by nikolovnikos** [comment]
Same issue here 
`"react-native-exponea-sdk": "^0.5.1",`
Xcode 12.5
To fix have to remove "$(TOOLCHAIN_DIR)/usr/lib/swift-5.0/$(PLATFORM_NAME)" from project.pbxproj file

**Comment by adeem** [comment]
I dont even have to update the package. What I did which worked was
1. Add swift file to create the bridge 
2. Remove  "$(TOOLCHAIN_DIR)/usr/lib/swift-5.0/$(PLATFORM_NAME)" from project.pbxproj file

And by doing above, this problem is solved for me and I will
